import { Row } from "@/types/types";

export const rowsData: Row[] = [
    {
      name: "John Doe",
      email: "john.doe@example.com",
      addedFrom: "System",
      internalId: "12345",
      phone: "123-456-7890",
      clientPortal: "Deactivated",
      assignee: "Alice",
      followers: "Jane Smith",
      status: "In Progress",
      Applications: "2",
      lastUpdated: "2024-12-20",
      avatarUrl: "https://github.com/shadcn.png",
    },
    {
      name: "Jane Smith",
      email: "jane.smith@example.com",
      addedFrom: "System",
      internalId: "54321",
      phone: "987-654-3210",
      clientPortal: "Deactivated",
      assignee: "Bob",
      followers: "John Doe",
      status: "Completed",
      Applications: "4",
      lastUpdated: "2024-12-21",
      avatarUrl: "https://github.com/shadcn.png",
    },
    {
      name: "John Doe",
      email: "john.doe@example.com",
      addedFrom: "System",
      internalId: "12345",
      phone: "123-456-7890",
      clientPortal: "Deactivated",
      assignee: "Alice",
      followers: "Jane Smith",
      status: "In Progress",
      Applications: "2",
      lastUpdated: "2024-12-20",
      avatarUrl: "https://github.com/shadcn.png",
    },
    {
      name: "Emily Davis",
      email: "emily.davis@example.com",
      addedFrom: "System",
      internalId: "98765",
      phone: "444-987-1234",
      clientPortal: "Deactivated",
      assignee: "Diana",
      followers: "Sam Wilson",
      status: "In Progress",
      Applications: "1",
      lastUpdated: "2024-12-23",
      avatarUrl: "https://github.com/shadcn.png",
    },
  ];
  